name: flutter_getx_codebase_samples
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  logger: ^1.3.0
  intl: 0.18.0
  dio: 5.2.1+1
  flutter_dotenv: ^5.0.2
  permission_handler: 10.2.0
  flutter_local_notifications: 14.0.0+1
  firebase_messaging: 14.4.1
  flutter_svg: 2.0.6
  file_picker: 5.3.2
  url_launcher: ^6.1.14
  firebase_core: 2.15.1
  shared_preferences: 2.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_flavorizr: 2.1.6
  flutter_launcher_icons: "^0.13.1"
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/.
    - assets/environments/.
    - assets/icons/.
    - assets/images/.
    - assets/fonts/.
  uses-material-design: true


flavorizr:
  app:
   android:
    flavorDimensions: flavor-type
   ios: null
  flavors:
   development:
     app:
       name: Development
     android:
       applicationId: com.codebase.dev
     ios:
       bundleId: com.codebase.dev
   production:
     app:
       name: Production
     android:
       applicationId: com.codebase
     ios:
       bundleId: com.codebase
