name: flutter_mapbox_amplify
version: 1.0.0+1
publish_to: none
description: Final Test Assignment from Fahmi Farhan Husin.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  intl: 0.18.0
  dio: 5.2.1+1
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.14
  shared_preferences: 2.1.1
  logger: 2.0.2+1
  mapbox_gl: ^0.16.0
  location: 5.0.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/.
    - assets/environments/.
    - assets/icons/.
    - assets/images/.
    - assets/fonts/.
  uses-material-design: true

