name: flutter_mapbox_amplify
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  logger: ^1.3.0
  intl: 0.18.0
  dio: 5.2.1+1
  flutter_dotenv: ^5.0.2
  flutter_svg: 2.0.6
  url_launcher: ^6.1.14
  shared_preferences: 2.1.1
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/.
    - assets/environments/.
    - assets/icons/.
    - assets/images/.
    - assets/fonts/.
  uses-material-design: true

